export default [

  // 🔋 BATTERY ISSUES
  { text: "battery drains quickly", label: "Battery Issue" },
  { text: "phone battery dies fast", label: "Battery Issue" },
  { text: "battery percentage drops suddenly", label: "Battery Issue" },
  { text: "battery overheats during use", label: "Battery Issue" },
  { text: "phone battery not holding charge", label: "Battery Issue" },
  { text: "battery drains overnight", label: "Battery Issue" },
  { text: "battery takes too long to charge", label: "Battery Issue" },
  { text: "battery drains even when idle", label: "Battery Issue" },
  { text: "battery gets hot while charging", label: "Battery Issue" },
  { text: "battery drains in just a few hours", label: "Battery Issue" },
  { text: "phone battery stuck at 1%", label: "Battery Issue" },
  { text: "battery jumps from 50 to 10 instantly", label: "Battery Issue" },
  { text: "battery drops fast during gaming", label: "Battery Issue" },
  { text: "battery level fluctuating randomly", label: "Battery Issue" },
  { text: "battery drains only when screen is off", label: "Battery Issue" },
  { text: "battery stuck at 100%", label: "Battery Issue" },
  { text: "phone shuts down even at 40% battery", label: "Battery Issue" },
  { text: "battery calibration issue", label: "Battery Issue" },
  { text: "phone battery swelling", label: "Battery Issue" },


  // 🔌 CHARGING ISSUES
  { text: "phone not charging", label: "Charging Issue" },
  { text: "charger connected but not charging", label: "Charging Issue" },
  { text: "charging cable not detected", label: "Charging Issue" },
  { text: "phone charges very slowly", label: "Charging Issue" },
  { text: "charging stops intermittently", label: "Charging Issue" },
  { text: "fast charging not working", label: "Charging Issue" },
  { text: "phone shows moisture detected", label: "Charging Issue" },
  { text: "charging port loose", label: "Charging Issue" },
  { text: "charging icon shows but battery not increasing", label: "Charging Issue" },
  { text: "charger disconnected warning repeatedly", label: "Charging Issue" },
  { text: "charging only works when cable is pressed", label: "Charging Issue" },
  { text: "wireless charging not working", label: "Charging Issue" },
  { text: "charging port loose and wobbly", label: "Charging Issue" },
  { text: "phone charges only with one specific cable", label: "Charging Issue" },
  { text: "phone stops charging when moved", label: "Charging Issue" },
  { text: "charging port blocked by dust", label: "Charging Issue" },
  { text: "reverse charging not working", label: "Charging Issue" },
  { text: "charging percentage stuck", label: "Charging Issue" },


  // ⚡ POWER / BOOT ISSUES
  { text: "phone not turning on", label: "Power Issue" },
  { text: "phone stuck on boot logo", label: "Boot Issue" },
  { text: "phone restarts randomly", label: "System Stability Issue" },
  { text: "phone shuts off even with battery left", label: "Power Issue" },
  { text: "phone stuck on black screen", label: "Boot Issue" },
  { text: "phone keeps rebooting", label: "System Stability Issue" },
  { text: "phone does not power on after charging", label: "Power Issue" },
  { text: "phone stuck on startup", label: "Boot Issue" },
  { text: "touch works randomly", label: "Display Issue" },
  { text: "half screen not working", label: "Display Issue" },
  { text: "screen goes black during use", label: "Display Issue" },
  { text: "screen keeps dimming automatically", label: "Display Issue" },
  { text: "screen gets bright by itself", label: "Display Issue" },
  { text: "double tap to wake not working", label: "Display Issue" },
  { text: "part of the screen is unresponsive", label: "Display Issue" },
  { text: "screen bleeding on edges", label: "Display Issue" },
  { text: "screen turning yellow tint", label: "Display Issue" },
  { text: "display shows ghost images", label: "Display Issue" },


  // 📱 DISPLAY ISSUES
  { text: "screen flickering", label: "Display Issue" },
  { text: "screen not responding", label: "Display Issue" },
  { text: "touchscreen not working", label: "Display Issue" },
  { text: "screen cracked after fall", label: "Display Issue" },
  { text: "screen shows lines", label: "Display Issue" },
  { text: "screen distorted colors", label: "Display Issue" },
  { text: "screen freezes during use", label: "Display Issue" },
  { text: "ghost touch issues", label: "Display Issue" },

  // 📶 CONNECTIVITY ISSUES
  { text: "wifi keeps disconnecting", label: "Connectivity Issue" },
  { text: "mobile data not working", label: "Connectivity Issue" },
  { text: "bluetooth not connecting", label: "Connectivity Issue" },
  { text: "wifi slow even with full signal", label: "Connectivity Issue" },
  { text: "sim card not detected", label: "Connectivity Issue" },
  { text: "network signal dropping", label: "Connectivity Issue" },
  { text: "hotspot not working", label: "Connectivity Issue" },
  { text: "unable to make calls due to network", label: "Connectivity Issue" },
  { text: "sim card keeps disconnecting", label: "Connectivity Issue" },
  { text: "no network detected", label: "Connectivity Issue" },
  { text: "phone shows emergency calls only", label: "Connectivity Issue" },
  { text: "wifi button not turning on", label: "Connectivity Issue" },
  { text: "bluetooth keeps turning off automatically", label: "Connectivity Issue" },
  { text: "mobile network unavailable", label: "Connectivity Issue" },
  { text: "cannot connect to 5G", label: "Connectivity Issue" },
  { text: "hotspot turns off automatically", label: "Connectivity Issue" },
  { text: "wifi shows connected but no internet", label: "Connectivity Issue" },
  { text: "airplane mode stuck on", label: "Connectivity Issue" },


  // 📷 CAMERA ISSUES
  { text: "camera blurry", label: "Camera Issue" },
  { text: "camera not opening", label: "Camera Issue" },
  { text: "camera app crashes", label: "Camera Issue" },
  { text: "photos are unclear", label: "Camera Issue" },
  { text: "video recording stops automatically", label: "Camera Issue" },
  { text: "front camera not working", label: "Camera Issue" },
  { text: "camera showing black screen", label: "Camera Issue" },
  { text: "camera takes too long to open", label: "Camera Issue" },
  { text: "camera shutter not working", label: "Camera Issue" },
  { text: "front camera blurry", label: "Camera Issue" },
  { text: "camera switching between lenses fails", label: "Camera Issue" },
  { text: "camera not focusing properly", label: "Camera Issue" },
  { text: "camera shows green/pink screen", label: "Camera Issue" },
  { text: "camera stuck at loading", label: "Camera Issue" },


  // 🔊 AUDIO ISSUES
  { text: "speaker not working", label: "Audio Issue" },
  { text: "low sound during calls", label: "Audio Issue" },
  { text: "microphone not working", label: "Audio Issue" },
  { text: "earpiece speaker low", label: "Audio Issue" },
  { text: "headphones not detected", label: "Audio Issue" },
  { text: "sound cracking from speaker", label: "Audio Issue" },
  { text: "sound completely muted", label: "Audio Issue" },
  { text: "sound distorted at high volume", label: "Audio Issue" },
  { text: "microphone works only on speaker mode", label: "Audio Issue" },
  { text: "caller cannot hear me", label: "Audio Issue" },
  { text: "phone speakers crackling", label: "Audio Issue" },
  { text: "headphone symbol stuck on screen", label: "Audio Issue" },
  { text: "receiver speaker not working", label: "Audio Issue" },


  // 🛠 HARDWARE ISSUES
  { text: "fingerprint sensor not working", label: "Hardware Issue" },
  { text: "volume buttons stuck", label: "Hardware Issue" },
  { text: "power button not responding", label: "Hardware Issue" },
  { text: "vibration motor not working", label: "Hardware Issue" },
  { text: "back panel coming off", label: "Hardware Issue" },
  { text: "sim tray damaged", label: "Hardware Issue" },
  { text: "charging port damaged", label: "Hardware Issue" },
  { text: "phone body slightly bent", label: "Hardware Issue" },
  { text: "buttons not clicking properly", label: "Hardware Issue" },
  { text: "fingerprint not recognizing", label: "Hardware Issue" },
  { text: "sim tray not ejecting", label: "Hardware Issue" },
  { text: "camera glass cracked", label: "Hardware Issue" },


  // 🚀 PERFORMANCE ISSUES
  { text: "phone lagging", label: "Performance Issue" },
  { text: "apps freezing", label: "Performance Issue" },
  { text: "phone overheating during gaming", label: "Overheating Issue" },
  { text: "system slow after update", label: "Performance Issue" },
  { text: "phone hanging frequently", label: "Performance Issue" },
  { text: "apps take long to load", label: "Performance Issue" },
  { text: "system UI keeps crashing", label: "System Stability Issue" },
  { text: "animations lag everywhere", label: "Performance Issue" },
  { text: "phone becomes slow after restart", label: "Performance Issue" },
  { text: "background apps keep closing", label: "System Issue" },
  { text: "auto brightness lagging", label: "System Issue" },
  { text: "phone freezes after unlocking", label: "Performance Issue" },
  { text: "phone gets stuck when scrolling", label: "Performance Issue" },
  { text: "scrolling not smooth on phone", label: "Performance Issue" },
  { text: "screen freezes while scrolling apps", label: "Performance Issue" },
  { text: "scrolling lag on my phone", label: "Performance Issue" },
  { text: "phone hangs when scrolling instagram", label: "Performance Issue" },
  { text: "scroll not working smoothly", label: "Performance Issue" },



  // 💾 STORAGE ISSUES
  { text: "storage full", label: "Storage Issue" },
  { text: "cannot install apps", label: "Storage Issue" },
  { text: "device storage warning", label: "Storage Issue" },
  { text: "files not downloading due to low memory", label: "Storage Issue" },
  { text: "cannot download anything due to storage error", label: "Storage Issue" },
  { text: "apps disappear due to low storage", label: "Storage Issue" },
  { text: "gallery shows insufficient storage", label: "Storage Issue" },
  { text: "storage keeps reducing automatically", label: "Storage Issue" },


  // 🌡 OVERHEATING ISSUES
  { text: "phone overheating", label: "Overheating Issue" },
  { text: "device heats during charging", label: "Overheating Issue" },
  { text: "phone gets hot while using apps", label: "Overheating Issue" },
  { text: "phone becomes warm during calls", label: "Overheating Issue" },
  { text: "phone heats while charging", label: "Overheating Issue" },
  { text: "phone hot while using camera", label: "Overheating Issue" },
  { text: "overheating warning displayed", label: "Overheating Issue" },
  { text: "phone hot even when idle", label: "Overheating Issue" },
  { text: "phone becomes hot in pocket", label: "Overheating Issue" },


  // 🧊 SYSTEM / APP ISSUES
  { text: "apps crashing", label: "App Issue" },
  { text: "system update failed", label: "System Issue" },
  { text: "apps not installing", label: "App Issue" },
  { text: "notifications not coming", label: "System Issue" },
  { text: "system UI not responding", label: "System Stability Issue" },

  // 💧 WATER DAMAGE
  { text: "phone fell in water", label: "Hardware Issue" },
  { text: "water inside charging port", label: "Charging Issue" },
  { text: "water damaged screen", label: "Display Issue" },
  { text: "camera foggy after water", label: "Camera Issue" },

  // 🌀 COMBINED MULTI-ISSUE SAMPLES (REAL WORLD)
  { text: "phone overheating and battery draining fast", label: "Battery Issue" },
  { text: "screen freezing and apps crashing", label: "Display Issue" },
  { text: "charging not working and phone not turning on", label: "Power Issue" },
  { text: "network dropping and mobile data slow", label: "Connectivity Issue" },
  { text: "camera blurry and app crashes", label: "Camera Issue" },
  { text: "phone stuck on boot logo and overheating", label: "Boot Issue" },
  { text: "battery draining and screen flickering", label: "Display Issue" },

  // 🚫 NOT MOBILE DEVICES
  { text: "laptop not turning on", label: "Not Mobile" },
  { text: "printer not printing", label: "Not Mobile" },
  { text: "tv screen has lines", label: "Not Mobile" },
  { text: "router not giving internet", label: "Not Mobile" },
  { text: "smartwatch screen frozen", label: "Not Mobile" },
  { text: "desktop overheating", label: "Not Mobile" },
  { text: "microwave not heating", label: "Not Mobile" },
  { text: "laptop overheating", label: "Not Mobile" },
  { text: "printer shows paper jam", label: "Not Mobile" },
  { text: "ac remote not working", label: "Not Mobile" },
  { text: "smartwatch not syncing", label: "Not Mobile" },
  { text: "router wifi light blinking", label: "Not Mobile" },
  { text: "desktop not booting", label: "Not Mobile" },
  { text: "laptop screen not turning on", label: "Not Mobile" },
  { text: "desktop pc making loud fan noise", label: "Not Mobile" },
  { text: "laptop keyboard not working", label: "Not Mobile" },
  { text: "pc keeps restarting automatically", label: "Not Mobile" },
  { text: "computer stuck on boot screen", label: "Not Mobile" },
  { text: "laptop battery not charging", label: "Not Mobile" },
  { text: "laptop overheating when gaming", label: "Not Mobile" },
  { text: "monitor showing no signal", label: "Not Mobile" },
  { text: "pc not detecting mouse", label: "Not Mobile" },
  { text: "laptop trackpad not responding", label: "Not Mobile" },
  { text: "printer printing blank pages", label: "Not Mobile" },
  { text: "printer not connecting to wifi", label: "Not Mobile" },
  { text: "printer showing paper jam error", label: "Not Mobile" },
  { text: "ink not coming out properly", label: "Not Mobile" },
  { text: "printer prints very slow", label: "Not Mobile" },
  { text: "laser printer making grinding noise", label: "Not Mobile" },
  { text: "printer not recognized by computer", label: "Not Mobile" },
  { text: "tv screen has vertical lines", label: "Not Mobile" },
  { text: "smart tv not connecting to wifi", label: "Not Mobile" },
  { text: "tv remote not responding", label: "Not Mobile" },
  { text: "tv shows no signal on hdmi", label: "Not Mobile" },
  { text: "tv display flickering", label: "Not Mobile" },
  { text: "tv turning off automatically", label: "Not Mobile" },
  { text: "smart tv apps not opening", label: "Not Mobile" },
  { text: "wifi router keeps restarting", label: "Not Mobile" },
  { text: "router no internet light blinking", label: "Not Mobile" },
  { text: "router range very low", label: "Not Mobile" },
  { text: "router login page not opening", label: "Not Mobile" },
  { text: "router overheating", label: "Not Mobile" },
  { text: "router not detecting broadband cable", label: "Not Mobile" },
  { text: "router connected but no internet", label: "Not Mobile" },
  { text: "washing machine not spinning", label: "Not Mobile" },
  { text: "ac not cooling properly", label: "Not Mobile" },
  { text: "fridge making loud noise", label: "Not Mobile" },
  { text: "microwave not heating food", label: "Not Mobile" },
  { text: "electric kettle not boiling water", label: "Not Mobile" },
  { text: "smartwatch battery draining fast", label: "Not Mobile" },
  { text: "blender not turning on", label: "Not Mobile" },
  { text: "fan making unusual noise", label: "Not Mobile" },
  { text: "geyser not heating water", label: "Not Mobile" },
  { text: "home theater sound not coming", label: "Not Mobile" },
  { text: "car audio system not working", label: "Not Mobile" },
  { text: "digital camera lens stuck", label: "Not Mobile" },
  { text: "tablet battery draining quickly", label: "Not Mobile" },
  { text: "smartwatch not syncing with phone", label: "Not Mobile" },
  { text: "drone not taking off", label: "Not Mobile" },
  { text: "gaming console overheating", label: "Not Mobile" },
  { text: "air purifier not turning on", label: "Not Mobile" },
  { text: "projector showing blurry image", label: "Not Mobile" },
  { text: "smart speaker not responding", label: "Not Mobile" },

];
